
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project_17
{

using System;
    using System.Collections.Generic;
    
public partial class Sales
{

    public int id { get; set; }

    public string Email { get; set; }

    public int code_product { get; set; }

    public string description_product { get; set; }

}

}
